# Generated by Django 5.2.8 on 2025-11-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='order placed', max_length=20),
        ),
    ]
